export const SYMBOL_ADD = ' + ';
export const SYMBOL_SUBTRACT = ' - ';
export const SYMBOL_MULTIPLY = ' * ';
export const SYMBOL_DIVIDE = ' / ';
export const SYMBOL_EQUAL = ' =';
export const SYMBOL_E = 'e^(';
export const SYMBOL_LOGARITHM = 'log(';
export const SYMBOL_NATURAL_LOGARITHM = 'ln(';
export const SYMBOL_POWER_2 = '²';
export const SYMBOL_POWER_3 = '³';
export const SYMBOL_POWER_Y = '^';
export const SYMBOL_POWER_MATH = ' ** ';
export const SYMBOL_SQUARE_ROOT_2 = '√';
export const SYMBOL_SQUARE_ROOT_3 = '∛';
export const SYMBOL_SQUARE_ROOT_Y = 'ʸ';
export const SYMBOL_ONE_DIVIDE_X = '1 /';
export const SYMBOL_RIGHT_BRACKET = ')';
export const MESSAGE = 'На ноль делить нельзя';
